"""baseline schema

Revision ID: bbd852692152
Revises: 
Create Date: 2026-06-29 17:17:55.330634
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd852692152'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('genre_match', sa.String(), nullable=True),
    sa.Column('parallel_slots', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('budget_mode', sa.Enum('words', 'minutes', name='budgetmode'), nullable=False),
    sa.Column('budget_credit', sa.Float(), nullable=False),
    sa.Column('queue_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wpm', sa.Integer(), nullable=False),
    sa.Column('cadence_cron', sa.String(), nullable=False),
    sa.Column('thumbs_down_drop_threshold', sa.Integer(), nullable=False),
    sa.Column('feed_secret', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('websub_subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_url', sa.String(), nullable=False),
    sa.Column('callback_url', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_url', 'callback_url', name='uq_topic_callback')
    )
    with op.batch_alter_table('websub_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_websub_subscription_topic_url'), ['topic_url'], unique=False)

    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calibre_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('tracked', sa.Boolean(), nullable=False),
    sa.Column('feed_url', sa.String(), nullable=True),
    sa.Column('last_seen_guid', sa.String(), nullable=True),
    sa.Column('last_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetch_status', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'active', 'completed', 'dropped', name='bookstatus'), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=True),
    sa.Column('quota_weight', sa.Float(), nullable=False),
    sa.Column('cursor_chapter_index', sa.Integer(), nullable=False),
    sa.Column('chapter_label_offset', sa.Integer(), nullable=False),
    sa.Column('cursor_floor', sa.Integer(), nullable=False),
    sa.Column('thumbs_up', sa.Integer(), nullable=False),
    sa.Column('thumbs_down', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calibre_id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_channel_id'), ['channel_id'], unique=False)

    op.create_table('drops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('feed_key', sa.String(), nullable=True),
    sa.Column('chapter_start', sa.Integer(), nullable=False),
    sa.Column('chapter_end', sa.Integer(), nullable=False),
    sa.Column('chapter_titles', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('feedback_token', sa.String(), nullable=False),
    sa.Column('reader_slug', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_token'),
    sa.UniqueConstraint('reader_slug')
    )
    with op.batch_alter_table('drops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drops_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drops_feed_key'), ['feed_key'], unique=False)

    op.create_table('feedback_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('drop_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('up', 'down', 'extra', 'drop', name='feedbackaction'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_event')
    with op.batch_alter_table('drops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drops_feed_key'))
        batch_op.drop_index(batch_op.f('ix_drops_channel_id'))

    op.drop_table('drops')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_channel_id'))

    op.drop_table('book')
    with op.batch_alter_table('websub_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_websub_subscription_topic_url'))

    op.drop_table('websub_subscription')
    op.drop_table('config')
    op.drop_table('channel')
    op.drop_table('app_state')
    # ### end Alembic commands ###
