"""add config.extra_boost_multiplier

Revision ID: ffdf857a9989
Revises: bbd852692152
Create Date: 2026-06-29 17:18:19.192938
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffdf857a9989'
down_revision: Union[str, None] = 'bbd852692152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills the existing single config row (NOT NULL would otherwise fail);
    # the model carries the same default for newly-inserted rows.
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'extra_boost_multiplier', sa.Float(), nullable=False, server_default='1.5'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('extra_boost_multiplier')

    # ### end Alembic commands ###
